### ISSUE TITLE
[feature request] support seperate build command for watch mode

### ISSUE THREAD

**Issue by maraisr** [cloudflare/miniflare#116]
> no idea about v2 — so please do direct me if already a thing.

when developing for wasm, the build command is generally geared to `--release` builds, which take a lot longer to build.

would be nice during local development if `--watch ` can have a special miniflare property to override this.

```toml
[build]
command = "cargo build --release"

[miniflare]
build_command = "cargo build"
```

**Comment by mrbbot** [comment]
Hey! 👋 You should be able to do this with `wrangler.toml` environments:

```toml
# wrangler.toml
[build]
command = "cargo build --release"

[env.dev.build]
command = "cargo build"
```

...then run Miniflare with `miniflare --wrangler-env dev`. Technically `build` is a [top-level configuration](https://developers.cloudflare.com/workers/cli-wrangler/configuration#keys) key, so this shouldn't work, but Miniflare ignores those rules. 😅
