### ISSUE TITLE
`[miniflare.mounts]` does not fire scheduled events for mounted workers

### ISSUE THREAD

**Issue by jed** [cloudflare/miniflare#163]
Scheduled events are not being fired properly for mounted workers. Given the following three files:

```toml
# parent/wrangler.toml
[miniflare.mounts]
child = "../child"
```

```toml
# child/wrangler.toml
[triggers]
crons = ["0 * * * *"]

[build.upload]
dir = "."
format = "modules"
main = "worker.js"
```

```js
// child/worker.js
export default {
  scheduled() {
    console.log('DONE')
  }
}
```

running `miniflare` in the `child` directory, and then `curl "http://localhost:8787/cdn-cgi/mf/scheduled"`, prints this to the console:

```
DONE
SCHD /cdn-cgi/mf/scheduled 200 OK
```

whereas running `miniflare` in the `parent` directory, and then `curl "http://localhost:8787/cdn-cgi/mf/scheduled"`, prints this to the console:

```
SCHD /cdn-cgi/mf/scheduled 200 OK
```

ie, the worker code is not fired, despite the fact that the scheduled endpoint is fired.
