### ISSUE TITLE
Support `[text_blobs]`

### ISSUE THREAD

**Issue by mrbbot** [cloudflare/miniflare#211]
Wrangler allows text bindings to be loaded from files. Miniflare should support these too.
```toml
[text_blobs]
TEXT = "./text.txt"
```
 See https://github.com/cloudflare/wrangler2/pull/518 and https://github.com/cloudflare/wrangler/pull/1543.
