### ISSUE TITLE
`DurableObjectNamespace.newUniqueId` throws in latest version of node

### ISSUE THREAD

**Issue by jed** [cloudflare/miniflare#215]
Due to [a recent change](https://github.com/nodejs/node/commit/b8de7aa4c2731883121bd7dcd19ec116f685eaa0) in node, `DurableObjectNamespace.newUniqueId` now throws when invoked.

To reproduce:

1. Create the following `wrangler.toml`:

```toml
[[durable_objects.bindings]]
name = "MyObject"
class_name = "MyObject"

[build.upload]
dir = ""
format = "modules"
main = "./index.js"
```

2. Create the following `index.js`:

```js
export class MyObject {}
export default {
  fetch(request, env) {
    return new Response(env.MyObject.newUniqueId())
  }
}
```

3. Run `miniflare`.
4. Run `curl http://127.0.0.1:8787`.
5. Observe error in console: `TypeMismatchError: The data argument must be an integer-type TypedArray`.
6. Repeat steps with node@16, observe that no error is thrown.
