### ISSUE TITLE
Unable to resolve "public/build/server.js" dependency "../__STATIC_CONTENT_MANIFEST": no matching module rules.

### ISSUE THREAD

**Issue by konsumer** [cloudflare/miniflare#230]
I am trying a bunch of combos to get `@cloudflare/kv-asset-handler` in both cloudflare & miniflare, and every combo of config I have tried seems to fail.

I am using esbuild & CF modules to make an SSR react app.

files
```
├── package.json
├── public
│   ├── build
│   │   ├── client.css
│   │   ├── client.css.map
│   │   ├── client.js
│   │   ├── client.js.map
│   │   ├── server.css
│   │   ├── server.css.map
│   │   ├── server.js
│   │   └── server.js.map
│   └── favicon.ico
├── src
│   ├── app.jsx
│   ├── client.jsx
│   ├── index.html
│   ├── pages
│   │   ├── 404.jsx
│   │   ├── 500.jsx
│   │   ├── about.jsx
│   │   ├── api.js
│   │   ├── dynamic
│   │   │   └── $id.jsx
│   │   └── index.jsx
│   ├── server.jsx
│   └── style.css
├── tools
│   ├── build.mjs
│   └── react-shim.js
└── wrangler.toml
```

wrangler.toml
```toml
name = "cf-socket"
type = "javascript"
compatibility_date = "2022-03-28"

# put your account-id here
account_id = ""

# use workers.dev hostname
workers_dev = true

# set your own DNS route
route = ""

# Can be used to specify a domain ID when deploying to a production domain (e.g. *.mydomain.com)
zone_id = ""

[site]
# The directory containing your static assets
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "public"
main = "./build/server.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]
```

build.js
```js
import { build } from 'esbuild'
import pluginGlobImport from 'esbuild-plugin-import-glob'

build({
  entryPoints: ['src/server.jsx', 'src/client.jsx'],
  outdir: 'public/build',

  plugins: [pluginGlobImport.default()],
  bundle: true,
  target: 'esnext',
  format: 'esm',
  sourcemap: true,
  loader: {
    '.html': 'text',
    '.gql': 'text'
  },
  inject: [
    'tools/react-shim.js'
  ],
  external: [
    '../__STATIC_CONTENT_MANIFEST'
  ]
})
```

In my script, if I do this it will work on wrangler (no build error, static assets working, etc)

```js
import ASSET_MANIFEST from '../__STATIC_CONTENT_MANIFEST'

export default {
async fetch (request, env, ctx) {
    try {
      return await getAssetFromKV(
        {
          request,
          waitUntil (promise) {
            return ctx.waitUntil(promise)
          }
        },
        {
          ASSET_NAMESPACE: env.__STATIC_CONTENT,
          ASSET_MANIFEST
        }
      )
    } catch (e) {
      return getPage('/404', 404, serverParams)
    }
  }
}
```

But if I try to run locally, I get the error. If I change the import-path and esbuild config to `__STATIC_CONTENT_MANIFEST` (no `..`) it works locally, but I get this when I try to deploy with wrangler:

```
> npx -y @cloudflare/wrangler publish

🌀  Running npm run build

> slimplate-tpl-cf-react@0.0.0 build
> node tools/build.mjs

✨  Build completed successfully!
🌀  Using namespace for Workers Site "__cf-socket-workers_sites_assets"
✨  Success
🌀  Uploading site files
Error: Something went wrong with the request to Cloudflare...
Uncaught Error: No such module "build/__STATIC_CONTENT_MANIFEST".
  at line 0
 [API code: 10021]
```
[Here](https://github.com/slimplate/slimplate-tpl-cf-react) is a demo-project. Do I need to structure my project differently?

**Comment by konsumer** [comment]
Got great advice from @mrbbot in discord (Thanks!)

Essentially, I need this in wrangler:

```toml
[build.upload]
format = "modules"
dir = "public/build"
main = "./server.js"
```

I updated my example project, if you are a future-person looking for this answer.
