### ISSUE TITLE
Workers using local modules cannot be mounted

### ISSUE THREAD

**Issue by jed** [cloudflare/miniflare#244]
When using this in my `wrangler.toml`:
```toml
[[build.upload.rules]]
type = "Data"
globs = ["**/*.html"]
```
And this in my `worker.mjs`:
```js
import HTML from "chat.html";
```
`miniflare` runs fine. But when I try to mount this worker from another worker like this:
```toml
[miniflare.mounts]
worker = "../worker"
```
I get an error like this:
```
Cause: RangeError: path should be a `path.relative()`d string, but got "../worker/dist/chat.html
```
