### ISSUE TITLE
wranglerConfigEnv not picking up env specific bindings on Jest@28 

### ISSUE THREAD

**Issue by SupremeTechnopriest** [cloudflare/miniflare#255]
Hey @mrbbot,

It looks like in the latest version of miniflare `wranglerConfigEnv` is not adding bindings to the global `getMiniflareBindings`.

`wrangler.toml`
```toml
[[env.dev.kv_namespaces]]
binding = "KEY_VALUE_STORE"
preview_id = "unused"
id = "unused"
```

`jest.config.json`
```json
{
  "testEnvironment": "miniflare",
  "testEnvironmentOptions": {
    "wranglerConfigEnv": "dev"
  }
}
```

`test`
```js
console.log(getMiniflareBindings()) // {}
```

However if I add a binding to the global env of the `wrangler.toml` it picks it up.

`wrangler.toml`
```toml
[[kv_namespaces]]
binding = "KEY_VALUE_STORE"
preview_id = "unused"
id = "unused"
```

`test`
```js
console.log(getMiniflareBindings()) // { KEY_VALUE_NAMESPACE: ... }
```

I just popped it into the global scope as a workaround for now, but this would be a problem when I actually need to publish this worker.  Thanks for looking into it!
