### ISSUE TITLE
Miniflare toml [Question]

### ISSUE THREAD

**Issue by TorbjornHoltmon** [cloudflare/miniflare#482]
~~This is better suited as a discussion.~~

~~I am trying to mount a worker and I am having issues translating the CLI commands to their respective TOML figgurations.~~

~~When you mount a worker we specify~~

```toml
# Paths resolved relative to wrangler.toml's directory
[miniflare.mounts]
graphql = "../graphql"
```
~~I therefore assumed that all miniflare cli commands can be configured in toml.~~

~~This will then read the wrangler.toml file and mount the worker. But there are multiple discrepancy between miniflare and the current wrangler 2 configuration we run.~~

~~We have therefore opted to use the cli to configure miniflare to make the two distinct from eachother
`miniflare  --wrangler-env staging --debug --compat-flag streams_enable_constructors --global-timers --global-async-io --kv-persist --cache-persist --modules dist/app.js",`~~

~~I have tried:~~
```toml
[miniflare]
wrangler-env = "staging"
global-timers = true
modules = true
compat-flag = ["streams_enable_constructors"]
format = "modules"
```

~~None of them seem to be picked up by miniflare.~~
~~Am i mistaken that miniflare can read from the toml in order to be configured?~~

~~If it can be configured, how would the TOML look?~~

~~Edit:~~

~~I think the only issue here is:~~
~~compat flags, and not being able to decide the wrangler-env of the mounted worker. (That i know)~~

I just overlooked the detail where `@` is used to define wrangler env for mounted workers
