### ISSUE TITLE
Support for rate limiting

### ISSUE THREAD

**Issue by gkiely** [cloudflare/miniflare#772]
Following this tutorial: https://developers.cloudflare.com/workers/runtime-apis/bindings/rate-limit/

```toml
main = "src/index.js"

# The rate limiting API is in open beta.
[[unsafe.bindings]]
name = "MY_RATE_LIMITER"
type = "ratelimit"
# An identifier you define, that is unique to your Cloudflare account.
# Must be an integer.
namespace_id = "1001"

# Limit: the number of tokens allowed within a given period in a single
# Cloudflare location
# Period: the duration of the period, in seconds. Must be either 10 or 60
simple = { limit = 100, period = 60 }
```

`env.MY_RATE_LIMITER` is not exposed as a binding.
