### ISSUE TITLE
Cannot access `generateKey` as we couldn't find a `wrangler dev` session for service "keys" to proxy to.

### ISSUE THREAD

**Issue by daliborgogic** [cloudflare/miniflare#782]
```generateKey``` is Remote-procedure call (RPC) not a fetch

```
at async ProxyServer.fetch (./node_modules/miniflare/src/workers/core/proxy.worker.ts:173:11)
```

```toml
[[services]]
binding = "Keys"
service = "keys"
```
