### ISSUE TITLE
Feature: support multiple watch dirs in wrangler.toml

### ISSUE THREAD

**Issue by hazcod** [cloudflare/miniflare#99]

**Comment by mrbbot** [comment]
Hey! 👋 I've just released version `2.1.0` including support for this.

```toml
[build]
watch_dir = "src1"

[miniflare]
build_watch_dirs = ["src2", "src3"] # These get merged with watch_dir above
```

You can find the [full changelog here](https://github.com/cloudflare/miniflare/releases/tag/v2.1.0).
